# запустить проект
run-dist:
	./build/install/app/bin/app

# удалить результаты предыдущей сборки, компиляция и сборка проекта
install:
	./gradlew clean install

# выполнить проверку стиля кодирования
lint:
	./gradlew checkstyleMain
